<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih Gambar</name>
   <tag></tag>
   <elementGuidId>3ed06b3a-3417-485c-82f5-d7ac63be7437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.gallery-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[3]/div/div[3]/div[2]/div[2]/div[2]/div/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>588b96ad-a883-4082-9206-7603cfe444df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gallery-button</value>
      <webElementGuid>75168ebd-010f-4df0-9d96-b5d14e33a3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Gambar</value>
      <webElementGuid>950bfba7-05a0-419a-9ca8-04af981ba997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;wrapper wrapper-content&quot;]/div[1]/div[@class=&quot;page-editor&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-collapse collapse in&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;rug&quot;]/div[1]/div[@class=&quot;gallery-content&quot;]/div[@class=&quot;gallery-header&quot;]/button[@class=&quot;gallery-button&quot;]</value>
      <webElementGuid>6dcaf74e-fd4e-417c-8af0-173f1b35a570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div[3]/div[2]/div[2]/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>74436ce9-0d6b-4189-859c-6955b770a242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto'])[1]/following::button[1]</value>
      <webElementGuid>e1aefb40-36b3-4f84-9a88-5893093545ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk non-varian yang belum ditemukan dimanapun'])[1]/following::button[1]</value>
      <webElementGuid>e50d9324-1917-4149-b6fc-a500e07742c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variasi Barang'])[1]/preceding::button[1]</value>
      <webElementGuid>b9743e67-100b-4ac1-bf9f-ba01ecfe6c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode SKU'])[1]/preceding::button[1]</value>
      <webElementGuid>0b3cf008-a7c8-426b-bb49-8128a8460cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Gambar']/parent::*</value>
      <webElementGuid>f19b2a4f-92fd-4bbe-bcbb-478cce961b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button</value>
      <webElementGuid>f875d1a2-67c9-4db0-9375-75544b862ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Pilih Gambar' or . = 'Pilih Gambar')]</value>
      <webElementGuid>f624155c-57ca-4bd8-972e-4b6578c5574c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
